name: Create Feature Branch with JIRA Ticket

on:
  issues:
    types: [opened]

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release-1.0/feature/${{ github.event.issue.number }}'

  create_jira_ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Create JIRA issue
        uses: atlassian/gajira-create@v2.0.1
        with:
          project: 'Your JIRA Project Key'
          issuetype: 'Task'
          summary: 'New issue from GitHub ${{ github.event.issue.title }}'
          description: 'Issue link: ${{ github.event.issue.html_url }}'
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
